# redis key
hostname = "mini.local"
# 可选 windows | macos | linux 
system = "macos"
# redis 服务器地址，存储失联次数
redis = "192.168.123.100"
port = 6379
passwd = ""
# 15 次运行程序未响应关闭服务器
max = 15

[ping]
# 局域网网关 IP
host = "192.168.123.1"
# 单次 Ping 重试次数
retry = 4
# 单次 Ping 超时时间
timeout = "1s"